# General system tasks
- name: Update packages
  apt:
    update_cache: yes

- name: Upgrade_ubuntu
  apt:
    upgrade=dist
    force_apt_get=yes


- name: Intall fav text editor nVim
  apt:
    name: nvim
    state: present

- name: Install git
  apt:
    name: git
    state: present

- name: Ensure group wheel exists
  group: 
    name: wheel
    state: present

- name: Ensure sudo group exists
  group:
    name: sudo
    state: present

- name: Ensure group docker exists
  group:
    name: docker
    state: present

- name: Create non-root sudo user
  user:
    name: "{{ username }}"
    password: "{{ password }}"
    shell: /bin/bash
    groups:
      - wheel
      - sudo
      - docker

- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', '/root/.ssh/authorized_keys') }}"

- name: Set up authorised ssh key for user
  ansible.builtin.shell: |
    mkdir -p /home/{{ username }}/.ssh
    cp /root/.ssh/authorized_keys /home/{{ username }}/.ssh/authorized_keys
    chmod 0755 /home/{{ username }}/.ssh/authorized_keys
  become: yes

- name: Allow 'wheel' group users to use passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: Disallow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
    backup: yes

- name: disable root login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
    backup: yes
  notify: restart sshd service

- name: enable ssh service
  ansible.builtin.service:
    name: sshd
    daemon_reload: yes
    enabled: yes